name: Fitmyrun
favicon: null
layout_spectrum: 0.16822234960272908
typography_spectrum: 0.7724236859939992
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.38913553836755455
  lightness: 0.781251527601853
  saturation: 0.8897444528993219
  rhythmicContrast: 0.43666386138647795
purpose: []
